<a href="https://colab.research.google.com/github/soujanya-vattikolla/Intermediate-Python-Programming-Course/blob/main/About_Python_Programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lists**<br>

*   Ordered
*   Mutable
*   Allows duplicate elements

In [ ]:
mylist = ['Cherry','apple','grapes']
print(mylist)

['Cherry', 'apple', 'grapes']


In [ ]:
mylist1 = list()
print(mylist1)

[]


In [ ]:
mylist2 = [5,'apple','apple','True']
print(mylist2)


[5, 'apple', 'apple', 'True']


In [ ]:
items = mylist[1]
print(items)


apple


In [ ]:
item = mylist2[-1]
print(item)

True


In [ ]:
for i in mylist2:
  print(i)

5
apple
apple
True


In [ ]:
if "apple" in mylist:
    print("yes")
else:
  print("no")

yes


In [ ]:
len(mylist)

3

In [ ]:
mylist.append('lemon')
print(mylist)

['Cherry', 'apple', 'grapes', 'lemon', 'lemon']


In [ ]:
mylist.insert(2,'rasperry')
print(mylist)

['Cherry', 'apple', 'rasperry', 'grapes', 'lemon', 'lemon']


In [ ]:
item = mylist.pop()
print(item)
print(mylist)

lemon
['Cherry', 'apple', 'rasperry', 'grapes']


In [ ]:
item = mylist.remove("apple")
print(item)

None


In [ ]:
print(mylist)

['Cherry', 'rasperry', 'grapes']


In [ ]:
item = mylist1.clear()
print(item)

None


In [ ]:
print(mylist2)
item = mylist2.reverse()
print(mylist2)

['True', 'apple', 'apple', 5]
[5, 'apple', 'apple', 'True']


In [ ]:
mylist.sort()
print(mylist)

['Cherry', 'grapes', 'rasperry']


In [ ]:
mylist1 = [5,-1,8,7,500]
mylist1.sort()
print(mylist1)

[-1, 5, 7, 8, 500]


In [ ]:
new_list = sorted(mylist1)
print(new_list)

[-1, 5, 7, 8, 500]


In [ ]:
my_lst = [0]*5
print(my_lst)

[0, 0, 0, 0, 0]


In [ ]:
my_lst2 = mylist1+my_lst
print(my_lst2)

[-1, 5, 7, 8, 500, 0, 0, 0, 0, 0]


In [ ]:
mylst = [1,2,3,4,5,6,7,8,9]
a = mylst[1:5]
print(a)

[2, 3, 4, 5]


In [ ]:
a = mylst[:]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a = mylst[::2]
print(a)

[1, 3, 5, 7, 9]


In [ ]:
a = mylst[::-1]
print(a)

[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
org_lst = ['Cherry', 'apple', 'grapes', 'lemon']
copy_lst = org_lst
print(copy_lst)

['Cherry', 'apple', 'grapes', 'lemon']


In [ ]:
copy_lst.append('orange')
print(copy_lst)
print(org_lst)

['Cherry', 'apple', 'grapes', 'lemon', 'orange']
['Cherry', 'apple', 'grapes', 'lemon', 'orange']


In [ ]:
copy_lst = org_lst.copy()
copy_lst.append('orange')
print(copy_lst)
print(org_lst)


['Cherry', 'apple', 'grapes', 'lemon', 'orange', 'orange']
['Cherry', 'apple', 'grapes', 'lemon', 'orange']


In [ ]:
copy_lst = list(org_lst)
copy_lst.append('orange')
print(copy_lst)
print(org_lst)

['Cherry', 'apple', 'grapes', 'lemon', 'orange', 'orange']
['Cherry', 'apple', 'grapes', 'lemon', 'orange']


In [ ]:
copy_lst = org_lst[:]
copy_lst.append('orange')
print(copy_lst)
print(org_lst)

['Cherry', 'apple', 'grapes', 'lemon', 'orange', 'orange']
['Cherry', 'apple', 'grapes', 'lemon', 'orange']


In [ ]:
print(mylst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
b = [i*i for i in mylst]
print(b)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


**Tuples**


*   Ordered
*   Immmutable
*   Allows duplicate elements

In [ ]:
mytuple = ("Max",28)
print(mytuple)

('Max', 28)


In [ ]:
mytuple = ("Max")
print(type(mytuple))

mytuple = ("Max",)
print(type(mytuple))

<class 'str'>
<class 'tuple'>


In [ ]:
mytuple = tuple(['Max',28,'Boston'])
print(mytuple)

('Max', 28, 'Boston')


In [ ]:
item = mytuple[1]
print(item)

28


In [ ]:
item = mytuple[-1]
print(item)

Boston


In [ ]:
mytuple[0] = "Tim"
print(mytuple)

TypeError: ignored

In [ ]:
for i in mytuple:
  print(i)

Max
28
Boston


In [ ]:
if "Max" in mytuple:
  print("yes")
else:
  print("no")

yes


In [ ]:
mytuple = ('a','p','p','l','e')
print(len(mytuple))

5


In [ ]:
print(mytuple.count('p'))

2


In [ ]:
print(mytuple.index('e'))

4


In [ ]:
my_lst = list(mytuple)
print(my_lst)

['a', 'p', 'p', 'l', 'e']


In [ ]:
mytuple = tuple(my_lst)
print(mytuple)

('a', 'p', 'p', 'l', 'e')


In [ ]:
a = (1,2,3,4,5,6,7,8,9,10)
b = a[2:5]
print(b)

(3, 4, 5)


In [ ]:
b = a[:]
print(b)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [ ]:
b = a[::3]
print(b)

(1, 4, 7, 10)


In [ ]:
b = a[::-1]
print(b)

(10, 9, 8, 7, 6, 5, 4, 3, 2, 1)


In [ ]:
mytuple = ("Max",28,"Boston")
name,age,city = mytuple
print(name)
print(age)
print(city)

Max
28
Boston


In [ ]:
my_tup = (0,1,2,3,4)
i1,*i2,i3 = my_tup
print(i1)
print(i2)
print(i3)

0
[1, 2, 3]
4


In [ ]:
import sys
my_lst = [0,1,"Max"]
my_tup = (0,1,"Max")
print(sys.getsizeof(my_lst),"bytes")
print(sys.getsizeof(my_tup),"bytes")

96 bytes
80 bytes


In [ ]:
import timeit
print(timeit.timeit(stmt="[0,1,2]",number=1000000))
print(timeit.timeit(stmt="(0,1,2)",number=1000000))

0.06505112600007124
0.012683730999924592


**Dictionaries**


*   Key value pairs
*   Unordered
*   Mutable

In [ ]:
mydict = {"name":"Max","age":25,"city":"Pune"}
print(mydict)

{'name': 'Max', 'age': 25, 'city': 'Pune'}


In [ ]:
mydict2 = dict(name="Max",age=25,city="Pune")
print(mydict2)

{'name': 'Max', 'age': 25, 'city': 'Pune'}


In [ ]:
values = mydict["name"]
print(values)


Max


In [ ]:
mydict["email"] = "max@xyz.com"
print(mydict)

{'name': 'Max', 'age': 25, 'city': 'Pune', 'email': 'max@xyz.com'}


In [ ]:
mydict["email"] = "cool@xyz.com"
print(mydict)

{'name': 'Max', 'age': 25, 'city': 'Pune', 'email': 'cool@xyz.com'}


In [ ]:
del mydict['name']
print(mydict)

{'age': 25, 'city': 'Pune', 'email': 'cool@xyz.com'}


In [ ]:
mydict.pop('city')
print(mydict)

{'age': 25, 'email': 'cool@xyz.com'}


In [ ]:
mydict.popitem()
print(mydict)

{'age': 25}


In [ ]:
mydict

{'age': 25}

In [ ]:
if 'age' in mydict:
  print(mydict['age'])

25


In [ ]:
for key in mydict:
  print(key)

age


In [ ]:
for values in mydict.values():
  print(values)

25


In [ ]:
for key,value in mydict.items():
  print(key,value)

age 25


In [ ]:
mydct_copy = mydict
print(mydct_copy)

{'age': 25}


In [ ]:
mydct_copy['email'] = "max@xyz.com"
print(mydct_copy)
print(mydict)

{'age': 25, 'email': 'max@xyz.com'}
{'age': 25, 'email': 'max@xyz.com'}


In [ ]:
mydct_copy = mydict.copy()
mydct_copy['email1'] = "max@xyz.com"
print(mydct_copy)
print(mydict)

{'age': 25, 'email': 'max@xyz.com', 'email1': 'max@xyz.com'}
{'age': 25, 'email': 'max@xyz.com'}


In [ ]:
mydct = {"name":"Max","age":55,"email":"abc@web.com"}
mydct1 = dict(name="Mad",age=85)

mydct.update(mydct1)
print(mydct)

{'name': 'Mad', 'age': 85, 'email': 'abc@web.com'}


In [ ]:
my_dict = {3:6,6:36,8:91}
print(my_dict)

{3: 6, 6: 36, 8: 91}


In [ ]:
value = my_dict[6]
print(value)

36


In [ ]:
mytuple = (8,7)
mydict = {mytuple:15}
print(mydict)

{(8, 7): 15}


**Sets**


*   Unordered
*   Mutable
*   No Duplicates

In [ ]:
myset = {1,2,3,1,2}
print(myset)

{1, 2, 3}


In [ ]:
myset = set([4,5,"hello"])
print(myset)

{'hello', 4, 5}


In [ ]:
myset = {}
type(myset)

dict

In [ ]:
myset = set()
print(myset)

set()


In [ ]:
myset.add(1)
myset.add(2)
myset.add(3)

In [ ]:
print(myset)

{1, 2, 3}


In [ ]:
myset.remove(3)
print(myset)

{1, 2}


In [ ]:
myset.discard(2)
print(myset)

{1}


In [ ]:
myset.clear()
print(myset)

set()


In [ ]:
myset.add(4)
myset.add(5)
myset.add(6)
print(myset)

{4, 5, 6}


In [ ]:
myset.pop()
print(myset)

{5, 6}


In [ ]:
for i in myset:
  print(i)

5
6


In [ ]:
if 5 in myset:
  print("yes")

yes


**Union and intersection**

In [ ]:
odd = {1,3,5,7,9}
even = {2,4,6,8,10}
primes = {2,3,5,7}

u = odd.union(even)
print(u)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
intrct = odd.intersection(even)
print(intrct)

set()


In [ ]:
intrct = odd.intersection(primes)
print(intrct)

{3, 5, 7}


In [ ]:
intrct = even.intersection(primes)
print(intrct)

{2}


In [ ]:
setA = {1,2,3,4,5,6,7,8,9}
setB = {1,2,3,5,67,8,9}

diff = setA.difference(setB)
print(diff)

{4, 6, 7}


In [ ]:
diff = setB.difference(setA)
print(diff)

{67}


In [ ]:
diff = setA.symmetric_difference(setB)
print(diff)

{67, 4, 6, 7}


In [ ]:
setA.update(setB)
print(setA)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 67}


In [ ]:
setA.intersection_update(setB)
print(setA)

{1, 2, 3, 67, 5, 8, 9}


In [ ]:
setA.difference_update(setB)
print(setA)

set()


In [ ]:
setA = {1,2,3,4,5,6,7,8,9}
setB = {1,2,3,5}
setC = {7,8}

In [ ]:
print(setA.issubset(setB))

False


In [ ]:
print(setB.issubset(setA))

True


In [ ]:
print(setA.issuperset(setB))

True


In [ ]:
print(setB.isdisjoint(setC))

True


In [ ]:
setD = setA
print(setD)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [ ]:
setD.add(10)
print(setD)
print(setA)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
setD = setA.copy()
setD.add(11)
print(setD)
print(setA)


{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
setD = set(setA)
setD.add(12)
print(setD)
print(setA)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
a = frozenset([1,2,3,4])
print(a)

frozenset({1, 2, 3, 4})


In [ ]:
a.remove(2)

AttributeError: ignored

**Strings**



*   Ordered
   
*   Immutable

*   Text representation

In [ ]:
my_string="Hello"
print(my_string)

Hello


In [ ]:
my_str = 'He\'s a boy'
print(my_str)

He's a boy


In [ ]:
my_str = '''hello \
hi'''
print(my_str)

hello hi


In [ ]:
my_string = "hello hi"
print(my_string[-1])

i


In [ ]:
print(my_string[2:5])

llo


In [ ]:
print(my_string[::-1])

ih olleh


In [ ]:
my_string1 = "Tom"
print(my_string+" "+my_string1)

hello hi Tom


In [ ]:
for i in my_string:
  print(i)

h
e
l
l
o
 
h
i


In [ ]:
if "o" in my_string:
  print("Yes")

Yes


In [ ]:
my_string = '   HelloHI    '
print(my_string)

   HelloHI    


In [ ]:
my_string = my_string.strip()
print(my_string)

HelloHI


In [ ]:
print(my_string.upper())

HELLOHI


In [ ]:
print(my_string.startswith('H'))

True


In [ ]:
print(my_string.endswith('o'))

False


In [ ]:
print(my_string.find('o'))

4


In [ ]:
print(my_string.count('l'))

2


In [ ]:
print(my_string.replace('HI','world'))

Helloworld


In [ ]:
my_string = "How are you doing"
lst = my_string.split()
new_str = ' '.join(lst)
print(lst)
print(new_str)

['How', 'are', 'you', 'doing']
How are you doing


In [ ]:
my_st = ['a']*6
print(my_st)

['a', 'a', 'a', 'a', 'a', 'a']


In [ ]:
my_strg = ''
for i in my_st:
  my_strg = ''.join(my_st)
print(my_strg)

aaaaaa


In [ ]:
var = "Tom"
my_st = "the variable is %s" %var
print(my_st)

the variable is Tom


In [ ]:
var = 3
my_st = "the variable is %.3f" %var
print(my_st)

the variable is 3.000


In [ ]:
var = 5
my_st = "the var is {}".format(var)
print(my_st)

the var is 5


In [ ]:
var = 6
my_st = f"the var is {var}"
print(my_st)

the var is 6


**Collections**



*   Counter
*   NamedTuple
*   OrderedDict
*   DefaultDict
*   Deque







In [ ]:
from collections import Counter

In [ ]:
a = "aaaabbbbccc"
my_counter = Counter(a)
print(my_counter)
print(my_counter.items())
print(my_counter.keys())
print(my_counter.most_common(1))
print(my_counter.most_common(1)[0][0])

Counter({'a': 4, 'b': 4, 'c': 3})
dict_items([('a', 4), ('b', 4), ('c', 3)])
dict_keys(['a', 'b', 'c'])
[('a', 4)]
a


In [ ]:
print(my_counter.elements())
print(list(my_counter.elements()))

['a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'c', 'c', 'c']


NamedTuple

In [ ]:
from collections import namedtuple

In [ ]:
Point = namedtuple('Point','x,y')
pt = Point(1,-4)
print(pt)
print(pt.x,pt.y)

Point(x=1, y=-4)
1 -4


**OrderedDict**

In [ ]:
from collections import OrderedDict

In [ ]:
ordereddict = OrderedDict()
ordereddict['f'] = 5
ordereddict['a'] = 1
ordereddict['b'] = 2
ordereddict['c'] = 3
ordereddict['d'] = 4
print(ordereddict)

OrderedDict([('f', 5), ('a', 1), ('b', 2), ('c', 3), ('d', 4)])


In [ ]:
ordereddict = {}
ordereddict['f'] = 5
ordereddict['a'] = 1
ordereddict['b'] = 2
ordereddict['c'] = 3
ordereddict['d'] = 4
print(ordereddict)

{'f': 5, 'a': 1, 'b': 2, 'c': 3, 'd': 4}


**DefaultDict**

In [ ]:
from collections import defaultdict

In [ ]:
d = defaultdict(int)
d['a'] = 1
d['b'] = 2
print(d['a'])
print(d['c'])


1
0


In [ ]:
d = defaultdict(float)
d['a'] = 1
d['b'] = 2
print(d['a'])
print(d['c'])

1
0.0


**Deque**

In [ ]:
from collections import deque

In [ ]:
d = deque()
d.append(1)
d.append(2)
print(d)

deque([1, 2])


In [ ]:
d.appendleft(4)
print(d)

deque([4, 1, 2])


In [ ]:
d.pop()

2

In [ ]:
print(d)

deque([4, 1])


In [ ]:
d.popleft()
print(d)

deque([1])


In [ ]:
d.clear()
print(d)

deque([])


In [ ]:
d.extend([4,5,6])
print(d)

deque([4, 5, 6])


In [ ]:
d.extendleft([7,8,9])
print(d)

deque([9, 8, 7, 4, 5, 6])


In [ ]:
d.rotate(1)
print(d)

deque([6, 9, 8, 7, 4, 5])


In [ ]:
d.rotate(-1)
print(d)

deque([9, 8, 7, 4, 5, 6])


**Itertools**


*   product
*   permutations
*   combinations
*   accumlate
*   groupby
*  infinite iterators





**product**

In [ ]:
from itertools import product

In [ ]:
a = [1,2]
b = [3,4]
prod = product(a,b)
print(prod)
print(list(prod))

[(1, 3), (1, 4), (2, 3), (2, 4)]


In [ ]:
a = [4,5]
b = [6]
prod = product(a,b,repeat=2)
print(list(prod))

[(4, 6, 4, 6), (4, 6, 5, 6), (5, 6, 4, 6), (5, 6, 5, 6)]


**Permutations**

In [ ]:
from itertools import permutations

In [ ]:
a = [1,2,3]
per = permutations(a)
print(list(per))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [ ]:
a = [1,2,3]
per = permutations(a,2)
print(list(per))

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


**Combinations**

In [ ]:
from itertools import combinations

In [ ]:
a = [1,2,3,4,5]
com = combinations(a,2)
print(list(com))


[(1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)]


In [ ]:
from itertools import combinations_with_replacement

a = [1,2,3,4,5]
com = combinations_with_replacement(a,2)
print(list(com))

[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (2, 2), (2, 3), (2, 4), (2, 5), (3, 3), (3, 4), (3, 5), (4, 4), (4, 5), (5, 5)]


**Accumulate**

In [ ]:
from itertools import accumulate

In [ ]:
a = [1,2,3,4]
acc = accumulate(a)
print(a)
print(list(acc))


[1, 2, 3, 4]
[1, 3, 6, 10]


In [ ]:
import operator

In [ ]:
a = [1,2,7,3,4]
acc = accumulate(a,func=max)
print(a)
print(list(acc))

[1, 2, 7, 3, 4]
[1, 2, 7, 7, 7]


**GroupBy**

In [ ]:
from itertools import groupby

In [ ]:
def small(x):
  return x <4

a = [1,2,3,4]
group_obj = groupby(a,key=small)
for key,value in group_obj:
    print(key,list(value))

True [1, 2, 3]
False [4]


In [ ]:
persons = [{'name':'Tim','age':25},{'name':'Tom','age':25},
           {'name':'Max','age':24},{'name':'Min','age':30}]

group_obj = groupby(persons,key=lambda x:x['age'])
for key,value in group_obj:
  print(key, list(value))
  


25 [{'name': 'Tim', 'age': 25}, {'name': 'Tom', 'age': 25}]
24 [{'name': 'Max', 'age': 24}]
30 [{'name': 'Min', 'age': 30}]


In [ ]:
from itertools import count,cycle,repeat

In [ ]:
for i in count(10):
  print(i)
  if i == 12:
    break

10
11
12


In [ ]:
a = [1,2,3]
for i in cycle(a):
  print(i)
  if i == 2:
    break

1
2


In [ ]:
a = [1,2,3]
for i in repeat(1,3):
  print(i)

1
1
1


**Lambda**

It is an anonymous function.<br>
lambda arguments:expression

In [ ]:
add10 = lambda x: x+15
print(add10(10))

25


In [ ]:
def add10_func(x):
  return x+10

print(add10_func(15))

25


In [ ]:
mult = lambda x,y:x*y
print(mult(2,5))

10


In [ ]:
points = [(1,2),(17,8),(19,10),(3,4),(5,6)]
points_sort = sorted(points)
print(points)
print(points_sort)

[(1, 2), (17, 8), (19, 10), (3, 4), (5, 6)]
[(1, 2), (3, 4), (5, 6), (17, 8), (19, 10)]


In [ ]:
points = [(1,2),(17,-1),(19,0),(3,4),(5,6)]
points_sort = sorted(points, key=lambda x: x[1])
print(points_sort)

[(17, -1), (19, 0), (1, 2), (3, 4), (5, 6)]


In [ ]:
def sort_by_y(x):
    return x[1]

points = [(1,2),(17,-1),(19,0),(3,4),(5,6)]
points_sort = sorted(points, key=sort_by_y)
print(points_sort)

[(17, -1), (19, 0), (1, 2), (3, 4), (5, 6)]


In [ ]:
points_sort = sorted(points,key=lambda x: x[0]+x[1])
print(points_sort)

[(1, 2), (3, 4), (5, 6), (17, -1), (19, 0)]


**Map function**

In [ ]:
a = [1,2,3,4,5]
b = map(lambda x:x*2,a)
print(list(b))

[2, 4, 6, 8, 10]


In [ ]:
c = [x*2 for x in a] #list comprehension
print(c)

[2, 4, 6, 8, 10]


**Filter**

In [ ]:
a = [1,2,3,4,5,6,7,8]
b = filter(lambda x:x%2==0,a)
print(list(b))

[2, 4, 6, 8]


In [ ]:
c = [ x for x in a if x%2==0]
print(c)

[2, 4, 6, 8]


**Reduce**

In [ ]:
from functools import reduce

In [ ]:
a = [1,2,3,4,5,6]
prod_a = reduce(lambda x,y:x*y,a)
print(prod_a)


720


**Exceptions**

Syntax and exceptions

**Syntax error**

In [ ]:
a = 5 
print(a))

SyntaxError: ignored

In [ ]:
a = 5 print(a)

SyntaxError: ignored

**Type error**

In [ ]:
a = 5 + '10'

TypeError: ignored

In [ ]:
import some

ModuleNotFoundError: ignored

In [ ]:
a = 5
b = f
print(b)

NameError: ignored

In [ ]:
f = open('file.txt')

FileNotFoundError: ignored

In [ ]:
a = [1,2,3]
a.remove(2)
print(a)

[1, 3]


In [ ]:
a.remove(2)


ValueError: ignored

In [ ]:
a[10]

IndexError: ignored

In [ ]:
my_dct = {'name':'Mad'}
print(my_dct['age'])

KeyError: ignored

In [ ]:
x = -5
if x < 0:
  raise Exception("X should be +ve")

Exception: ignored

In [ ]:
x = 5  # no exception is raised
if x < 0:
  raise Exception("X should be +ve")

In [ ]:
x = -5
assert(x>=0),'x is not positive'



AssertionError: ignored

In [ ]:
try:
  a = 5/0
except Exception as e:
  print(e)

division by zero


In [ ]:
try:
  a = 5/4
  b = 5+"a"
except Exception as e:
    print(e)
else:
  print("No error")
finally:
    print("Done")

unsupported operand type(s) for +: 'int' and 'str'
Done


In [ ]:
class ValueError(Exception):
  pass

def text_value(x):
  if x>100:
    raise ValueError('value is high')

try:
  text_value(200)
except Exception as e:
  print(e)



value is high


**Logging**

The logging module in Python is a powerful built-in module so you can quickly add logging to your application.

In [ ]:
import logging

**Log Level**
There are 5 different log levels indicating the serverity of events. By default, the system logs only events with level WARNING and above.

In [ ]:
logging.debug("This is a debug message")
logging.info("This is an info message")
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')

ERROR:root:This is an error message
CRITICAL:root:This is a critical message


**Configuration**<br>
With basicConfig(**kwargs) you can customize the root logger.

In [ ]:
import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s- %(name)s- %(levelname)s - %(message)s',datefmt='%m%d%Y %H:%M:%S')
logging.debug("This is a debug message")
logging.info("This is an info message")
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')

ERROR:root:This is an error message
CRITICAL:root:This is a critical message


**Logging in modules and logger hierarchy**<br>
With multiple modules is to create an internal logger using the
__name__ global variable.

**Propagation**<br>
By default, all created loggers will pass the log events to the handlers of higher loggers, in addition to any handlers attached to the created logger. You can deactivate this by setting propagate = False

**Log Handler**

In [ ]:
import logging

stream_handler = logging.StreamHandler()
file_handler = logging.FileHandler()

stream_handler.setLevel



**JSON**

JSON (JavaScript Object Notation) is a data format for data exchange. <br>
Advantages of JSON:<br>

JSON exists as a "sequence of bytes" which is very useful in the case we need to transmit (stream) data over a network.<br>
Compared to XML, JSON is much smaller, translating into faster data transfers, and better experiences.<br>
JSON is extremely human-friendly since it is textual, and simultaneously machine-friendly.

In [ ]:
import json

In [ ]:
# JSON Format
{
    "firstname":"Max",
    "age":25,
    "children":[
        {
            "firstname":"Alex"
        },
        {
            "firstname":"Min"
        }
    ]

}

{'age': 25,
 'children': [{'firstname': 'Alex'}, {'firstname': 'Min'}],
 'firstname': 'Max'}

From Python to JSON (Serialization, Encode)<br>
Convert Python objects into a JSON string with the **json.dumps()** method.

In [ ]:
import json

person = {"name":"John","age":30,"city":"Pune","title":["engineer","programmer"]}

perJSON = json.dumps(person,indent=4,sort_keys=True)

print(perJSON)

{
    "age": 30,
    "city": "Pune",
    "name": "John",
    "title": [
        "engineer",
        "programmer"
    ]
}


In [ ]:
with open('person.json','w') as file:
  json.dump(person,file,indent=4)

**FROM JSON to Python (Deserialization, Decode)**<br>
Convert a JSON string into a Python object with the **json.loads()** method. The result will be a Python dictionary.

In [ ]:
person = json.loads(perJSON)
print(person)

{'age': 30, 'city': 'Pune', 'name': 'John', 'title': ['engineer', 'programmer']}


In [ ]:
with open('person.json','r') as file:
  person = json.load(file)
  print(person)

{'name': 'John', 'age': 30, 'city': 'Pune', 'title': ['engineer', 'programmer']}


**Random numbers**

**The random module**

In [ ]:
import random

a = random.random()
print(a)

0.6606349456780772


In [ ]:
a = random.uniform(1,5)
print(a)

2.8192300442355473


In [ ]:
a = random.randint(1,5)
print(a)

4


In [ ]:
a = random.randrange(1,5)
print(a)

2


In [ ]:
a = random.normalvariate(0,1)
print(a)

-0.8827164658448969


In [ ]:
a = random.choice(list("ABCDEF"))
print(a)

C


In [ ]:
a = random.sample(list("ABCDEF"),3)
print(a)

['E', 'C', 'B']


In [ ]:
a = random.choices(list("ABCDEF"),k=4)
print(a)

random.shuffle(a)
print(a)

['D', 'E', 'D', 'D']
['D', 'E', 'D', 'D']


**The seed generator**<br>
With random.seed(), will produce the same trail of data.

In [ ]:
random.seed(1)
print(random.random())
print(random.randint(1,10))
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.13436424411240122
2


**The secrets module**

The secrets module is used for generating cryptographically strong random numbers suitable for managing data such as passwords, account authentication, security tokens, and related secrets.

In [ ]:
import secrets

In [ ]:
a = secrets.randbelow(10)
print(a)

9


In [ ]:
a = secrets.randbits(5)
print(a)

25


In [ ]:
a = secrets.choice(list("ABCDEF"))
print(a)

F


**Random numbers with NumPy**

In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(3)
print(a)

[0.70658699 0.29641811 0.3978122 ]


In [ ]:
a = np.random.rand(3,3)
print(a)

[[0.32598862 0.71994823 0.7848131 ]
 [0.00287456 0.35756375 0.27258754]
 [0.57390817 0.26107198 0.78630573]]


In [ ]:
a = np.random.randint(0,10,(3,3))
print(a)

[[3 3 9]
 [7 1 8]
 [5 6 7]]


In [ ]:
a = np.array([[1,2,3],[7,8,9],[9,2,4]])
np.random.shuffle(a)
print(a)

[[9 2 4]
 [1 2 3]
 [7 8 9]]


**Decorators**

It allows to add new functionality to an existing function.<br>
There are 2 kinds of decorators:<br>

Function decoratos<br>
Class decorators

A function is decorated with the @ symbol:<br>

@my_decorator<br>
def my_function():<br>
    pass

**Function decorators**

In [ ]:
def start_end_decorator(func):

  def wrapper():
    print('Start')
    func()
    print('End')
  return wrapper
@start_end_decorator
def print_name():
  print('Alex')

#print_name = start_end_decorator(print_name)  
print_name()

Start
Alex
End


**Class decorators**<br>
We can also use a class as a decorator. Therefore, we have to implement the __call__() method to make our object callable.

**Generators**

A generator is defined like a normal function but with the yield statement instead of return.<br>

def my_generator():<br>
  yield 1<br>
  yield 2

In [ ]:
def my_generator():
    yield 1
    yield 2

g = my_generator()

for i in g:
  print(i)

1
2


without a generator

In [ ]:
import sys
def firstn(n):
  nums = []
  num = 0
  while num < n:
    nums.append(num)
    num += 1
  return nums

print(firstn(10))
print(sum(firstn(10)))
print(sys.getsizeof(firstn(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
45
200


with a generator

In [ ]:
def firstn_gen(n):
  num = 0
  while num < n:
    yield num
    num += 1
  
print(sum(firstn_gen(10)))
print(sys.getsizeof(firstn_gen(10)))

45
128


In [ ]:
mygenertr = (i for i in range(10) if i%2 == 0)
print(list(mygenertr))

[0, 2, 4, 6, 8]


**Threading vs Multiprocessing**

**Process**<br>
A Process is an instance of a program, e.g. a Python interpreter. They are independent from each other and do not share the same memory.

**Threads**<br>
A thread is an entity within a process that can be scheduled for execution (Also known as "lightweight process").<br>
A Process can spawn multiple threads. <br>
The main difference is that all threads within a process share the same memory.

**GIL - Global interpreter lock**<br>
A lock that allows only one thread to execute at a time to execute in Python.

In [ ]:
from multiprocessing import Process
import os

def square_numbers():
  for i in range(100):
      i * i

processes = []
num_processes = os.cpu_count()

# create processess
for i in range(num_processes):
  p = Process(target=square_numbers)
  processes.append(p)

for p in processes:
  p.start() 

for p in processes:
  p.join()

print('end')


end


**Function Arguments**

**Arguments and parameters**<br>
Parameters are the variables that are defined or used inside parentheses while defining a function.<br>
Arguments are the value passed for these parameters while calling a function

In [ ]:
def print_name(name): # name is the parameter
    print(name)

print_name('Alex') # 'Alex' is the argument

Alex


**Positional and keyword arguments**<br>

In [ ]:
def foo(a,b,c):
  print(a,b,c)

foo(1,2,3) # positional arguments

foo(a=1,b=2,c=3) # keyword arguments

foo(1,c=3,b=2)

1 2 3
1 2 3
1 2 3


**Default arguments**<br>

In [ ]:
def foo(a,b,c=3):
  print(a,b,c)

foo(1,2,8)  

1 2 8


Variable-length arguments (*args and **kwargs) **bold text**

In [ ]:
def foo(a,b,*args,**kwargs):
    print(a,b)
    for arg in args:
      print(arg)
    for key in kwargs:
      print(key,kwargs[key])
foo(7,9,1,4,2,six=6,one=1)


7 9
1
4
2
six 6
one 1


**Unpacking into agruments**

In [ ]:
def foo(a,b,c):
  print(a,b,c)

# list/tuple unpacking, length must match
my_lst = [0,1,2]
foo(*my_lst)

# dict unpacking, keys and length must match
my_dct = {"a":1,"b":2,"c":3}
foo(**my_dct)

0 1 2
1 2 3


**Local vs global variables**

In [ ]:
def foo():
  global number
  x = number
  number = 3
  print('number inside function:',x)


number = 0
foo()
print("global number is",number)


number inside function: 0
global number is 3


**Parameter passing**

In [ ]:
def foo(x):
  x = 5
  x += 5 # since x is immutable and a new variable must be created

var = 10
print(var)
foo(var)
print(var)

10
10


In [ ]:
def foo(a_list):
  a_list.append(4)   # mutable objects -> change

my_list = [1,2,3]
foo(my_list)
print(my_list)

[1, 2, 3, 4]


The Asterisk (*) operator 

In [ ]:
# list
onetwos = [1,2]*5
print(onetwos)

# tuple
onetwos = (1,2)*5
print(onetwos)

# string
AB = "AB"*10
print(AB)

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]
(1, 2, 1, 2, 1, 2, 1, 2, 1, 2)
ABABABABABABABABABAB


In [ ]:
#*args , **kwargs , and keyword-only arguments


def fpp(a,b,*args,**kwargs):
  print(a)
  print(b)
  for arg in args:
    print(arg)
  for args in kwargs:
    print(args,kwargs[args])

fpp(5,7,8,9,10,six=6)

def fpp1(a,b,*,c):
  print(a,b,c)

fpp1(1,3,c=5)

5
7
8
9
10
six 6
1 3 5


In [ ]:
def foo(a,b,c):
  print(a,b,c)

my_lst = [1,2,3]
foo(*my_lst)

my_st = "ACD"
foo(*my_st)

my_dct = {"a":1,"b":2,"c":3}
foo(**my_dct)



1 2 3
A C D
1 2 3


In [ ]:
numbers = (1,2,3,4,5,6)
*begin,last = numbers
print(begin)
print(last)

print()

first,*end = numbers
print(first)
print(end)

print()

first,*middle,last = numbers
print(first)
print(middle)
print(last)


[1, 2, 3, 4, 5]
6

1
[2, 3, 4, 5, 6]

1
[2, 3, 4, 5]
6


Merge iterables into a list / Merge dictionaries

In [ ]:
my_tup = (1,2,3)
my_set = {4,5,6}
my_lst = [*my_tup,*my_set]
print(my_lst)

[1, 2, 3, 4, 5, 6]


In [ ]:
my_dct = {"a":1,"b":2}
my_dct1 = {"three":3,"one":1}
my_dc = {**my_dct,**my_dct1}
print(my_dc)

{'a': 1, 'b': 2, 'three': 3, 'one': 1}


**Shallow vs Deep Copying **

In [ ]:
org = 5
cpy  = org
cpy = 10
print(org)
print(cpy)

print()
# Assignment operation

lst_a = [1,2,3,4,5]
lst_b = lst_a

lst_a[0] = 20
print(lst_a)
print(lst_b)

5
10

[20, 2, 3, 4, 5]
[20, 2, 3, 4, 5]


**Shallow copy**

In [ ]:
import copy

lst_a = [1,2,3,4,5]
lst_b = copy.copy(lst_a)

lst_a[0] = 20
print(lst_a)
print(lst_b)

[20, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [ ]:
list_a = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
list_b = copy.copy(list_a)
list_a[0][0] = 30
print(list_a)
print(list_b)

[[30, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[30, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


Deep copies

In [ ]:
list_a = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
list_b = copy.deepcopy(list_a)
list_a[0][0] = 30
print(list_a)
print(list_b)

[[30, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


**Context Managers**

Context managers are a great tool for resource management. They allow you to allocate and release resources precisely when you want to. A well-known example is the with open() statemtent:

In [ ]:
with open('note.txt','w') as file:
  file.write('start')

file = open('note.txt','w')
try:
  file.write('start')
finally:
  file.close() 

**Examples of context managers**<br>
Open and close files<br>
open and close database connections<br>
Acquire and release locks: